cmake_minimum_required(VERSION 3.20)

PROJECT(TraderZMQ LANGUAGES CXX)

SET(SRC
	${PROJECT_SOURCE_DIR}/TraderZMQ.cpp
	${PROJECT_SOURCE_DIR}/TraderZMQ.h
)

SET(LIBRARY_OUTPUT_PATH ${CMAKE_BINARY_DIR}/build_${PLATFORM}/${CMAKE_BUILD_TYPE}/bin)

ADD_LIBRARY(TraderZMQ SHARED ${SRC})
TARGET_LINK_LIBRARIES(TraderZMQ
	PUBLIC WT::ZMQ
	PRIVATE WT::fmt WT::RapidJSON WT::Platform
)

IF (MSVC)
ELSE (GNUCC)
	SET_TARGET_PROPERTIES(TraderZMQ PROPERTIES
		CXX_VISIBILITY_PRESET hidden
		C_VISIBILITY_PRESET hidden
		VISIBILITY_INLINES_HIDDEN 1)
ENDIF()
