cmake_minimum_required(VERSION 3.21)

if(NOT DEFINED WT_PRESETS_FILE OR NOT EXISTS "${WT_PRESETS_FILE}")
	message(FATAL_ERROR "WT_PRESETS_FILE must name an existing CMakePresets.json")
endif()

file(READ "${WT_PRESETS_FILE}" WT_PRESETS_JSON)

function(WT_FIND_PRESET WT_KIND WT_NAME WT_OUTPUT)
	string(JSON WT_PRESET_COUNT LENGTH "${WT_PRESETS_JSON}" "${WT_KIND}")
	math(EXPR WT_PRESET_LAST "${WT_PRESET_COUNT} - 1")
	foreach(WT_PRESET_INDEX RANGE 0 ${WT_PRESET_LAST})
		string(JSON WT_PRESET_NAME GET "${WT_PRESETS_JSON}" "${WT_KIND}" ${WT_PRESET_INDEX} name)
		if(WT_PRESET_NAME STREQUAL WT_NAME)
			set(${WT_OUTPUT} ${WT_PRESET_INDEX} PARENT_SCOPE)
			return()
		endif()
	endforeach()
	message(FATAL_ERROR "Missing ${WT_KIND} entry '${WT_NAME}'")
endfunction()

function(WT_ASSERT_PRESET_MISSING WT_KIND WT_NAME)
	string(JSON WT_PRESET_COUNT LENGTH "${WT_PRESETS_JSON}" "${WT_KIND}")
	math(EXPR WT_PRESET_LAST "${WT_PRESET_COUNT} - 1")
	foreach(WT_PRESET_INDEX RANGE 0 ${WT_PRESET_LAST})
		string(JSON WT_PRESET_NAME GET "${WT_PRESETS_JSON}" "${WT_KIND}" ${WT_PRESET_INDEX} name)
		if(WT_PRESET_NAME STREQUAL WT_NAME)
			message(FATAL_ERROR "Unexpected ${WT_KIND} entry '${WT_NAME}'")
		endif()
	endforeach()
endfunction()

function(WT_ASSERT_JSON_VALUE WT_EXPECTED)
	set(WT_PATH ${ARGN})
	string(JSON WT_ACTUAL GET "${WT_PRESETS_JSON}" ${WT_PATH})
	if(NOT WT_ACTUAL STREQUAL WT_EXPECTED)
		message(FATAL_ERROR "Expected '${WT_EXPECTED}' at ${WT_PATH}, got '${WT_ACTUAL}'")
	endif()
endfunction()

WT_FIND_PRESET(configurePresets linux-x64-base WT_LINUX_BASE_INDEX)
WT_ASSERT_JSON_VALUE(ON configurePresets ${WT_LINUX_BASE_INDEX} hidden)
WT_ASSERT_JSON_VALUE("Unix Makefiles" configurePresets ${WT_LINUX_BASE_INDEX} generator)
WT_ASSERT_JSON_VALUE(ON configurePresets ${WT_LINUX_BASE_INDEX} cacheVariables BUILD_TESTING)
WT_ASSERT_JSON_VALUE(ON configurePresets ${WT_LINUX_BASE_INDEX} cacheVariables WT_ENABLE_WARNINGS)
WT_ASSERT_JSON_VALUE(BASELINE configurePresets ${WT_LINUX_BASE_INDEX} cacheVariables WT_WARNING_LEVEL)

WT_FIND_PRESET(configurePresets windows-x64-base WT_WINDOWS_BASE_INDEX)
WT_ASSERT_JSON_VALUE(ON configurePresets ${WT_WINDOWS_BASE_INDEX} hidden)
WT_ASSERT_JSON_VALUE("Visual Studio 18 2026" configurePresets ${WT_WINDOWS_BASE_INDEX} generator)
WT_ASSERT_JSON_VALUE(x64 configurePresets ${WT_WINDOWS_BASE_INDEX} architecture value)
WT_ASSERT_JSON_VALUE(ON configurePresets ${WT_WINDOWS_BASE_INDEX} cacheVariables BUILD_TESTING)
WT_ASSERT_JSON_VALUE(ON configurePresets ${WT_WINDOWS_BASE_INDEX} cacheVariables WT_ENABLE_WARNINGS)
WT_ASSERT_JSON_VALUE(BASELINE configurePresets ${WT_WINDOWS_BASE_INDEX} cacheVariables WT_WARNING_LEVEL)
WT_ASSERT_JSON_VALUE("\$env{VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake" configurePresets ${WT_WINDOWS_BASE_INDEX} cacheVariables CMAKE_TOOLCHAIN_FILE)

foreach(WT_PLATFORM IN ITEMS linux-x64 windows-x64)
	foreach(WT_PRESET_KIND IN ITEMS configurePresets buildPresets testPresets)
		WT_ASSERT_PRESET_MISSING(${WT_PRESET_KIND} ${WT_PLATFORM}-release)
	endforeach()

	foreach(WT_VARIANT IN ITEMS debug cxx20 cxx23)
		set(WT_PRESET_NAME ${WT_PLATFORM}-${WT_VARIANT})
		foreach(WT_PRESET_KIND IN ITEMS configurePresets buildPresets testPresets)
			WT_FIND_PRESET(${WT_PRESET_KIND} ${WT_PRESET_NAME} WT_PRESET_INDEX)
		endforeach()
	endforeach()

	WT_FIND_PRESET(configurePresets ${WT_PLATFORM}-debug WT_DEBUG_INDEX)
	WT_ASSERT_JSON_VALUE(17 configurePresets ${WT_DEBUG_INDEX} cacheVariables WT_CXX_STANDARD)
	WT_ASSERT_JSON_VALUE(ON configurePresets ${WT_DEBUG_INDEX} cacheVariables WT_WARNINGS_AS_ERRORS)

	WT_FIND_PRESET(configurePresets ${WT_PLATFORM}-cxx20 WT_CXX20_INDEX)
	WT_ASSERT_JSON_VALUE(20 configurePresets ${WT_CXX20_INDEX} cacheVariables WT_CXX_STANDARD)
	WT_ASSERT_JSON_VALUE(ON configurePresets ${WT_CXX20_INDEX} cacheVariables WT_WARNINGS_AS_ERRORS)

	WT_FIND_PRESET(configurePresets ${WT_PLATFORM}-cxx23 WT_CXX23_INDEX)
	WT_ASSERT_JSON_VALUE(23 configurePresets ${WT_CXX23_INDEX} cacheVariables WT_CXX_STANDARD)
	WT_ASSERT_JSON_VALUE(ON configurePresets ${WT_CXX23_INDEX} cacheVariables WT_WARNINGS_AS_ERRORS)
endforeach()

WT_FIND_PRESET(configurePresets linux-x64-debug WT_LINUX_DEBUG_INDEX)
WT_ASSERT_JSON_VALUE(Debug configurePresets ${WT_LINUX_DEBUG_INDEX} cacheVariables CMAKE_BUILD_TYPE)
WT_FIND_PRESET(configurePresets linux-x64-cxx20 WT_LINUX_CXX20_INDEX)
WT_ASSERT_JSON_VALUE(Release configurePresets ${WT_LINUX_CXX20_INDEX} cacheVariables CMAKE_BUILD_TYPE)
WT_FIND_PRESET(configurePresets linux-x64-cxx23 WT_LINUX_CXX23_INDEX)
WT_ASSERT_JSON_VALUE(Release configurePresets ${WT_LINUX_CXX23_INDEX} cacheVariables CMAKE_BUILD_TYPE)

set(WT_WINDOWS_VARIANTS debug cxx20 cxx23)
set(WT_WINDOWS_CONFIGURATIONS Debug Release Release)
foreach(WT_VARIANT WT_CONFIGURATION IN ZIP_LISTS WT_WINDOWS_VARIANTS WT_WINDOWS_CONFIGURATIONS)
	WT_FIND_PRESET(buildPresets windows-x64-${WT_VARIANT} WT_BUILD_INDEX)
	WT_ASSERT_JSON_VALUE(${WT_CONFIGURATION} buildPresets ${WT_BUILD_INDEX} configuration)
	WT_FIND_PRESET(testPresets windows-x64-${WT_VARIANT} WT_TEST_INDEX)
	WT_ASSERT_JSON_VALUE(${WT_CONFIGURATION} testPresets ${WT_TEST_INDEX} configuration)
endforeach()
