if(NOT WT_SOURCE_DIR)
	message(FATAL_ERROR "WT_SOURCE_DIR is required")
endif()

file(GLOB_RECURSE WT_CMAKE_LISTS "${WT_SOURCE_DIR}/*/CMakeLists.txt")
set(WT_DIRECTORY_STATE_VIOLATIONS "")
set(WT_CMAKE_HYGIENE_VIOLATIONS "")
foreach(WT_CMAKE_LIST IN LISTS WT_CMAKE_LISTS)
	file(RELATIVE_PATH WT_CMAKE_LIST_RELATIVE "${WT_SOURCE_DIR}" "${WT_CMAKE_LIST}")
	if(WT_CMAKE_LIST_RELATIVE MATCHES "^(API|out)/")
		continue()
	endif()
	file(READ "${WT_CMAKE_LIST}" WT_CMAKE_CONTENT)
	if(WT_CMAKE_CONTENT MATCHES "(^|\n)[ \t]*(INCLUDE_DIRECTORIES|LINK_DIRECTORIES|LINK_LIBRARIES|ADD_DEFINITIONS)[ \t]*\\(")
		list(APPEND WT_DIRECTORY_STATE_VIOLATIONS "${WT_CMAKE_LIST_RELATIVE}")
	endif()
	if(WT_CMAKE_CONTENT MATCHES "(LIBRARY_OUTPUT_PATH|EXECUTABLE_OUTPUT_PATH|LINK_FLAGS_RELEASE)" OR
		WT_CMAKE_CONTENT MATCHES "file[ 	]*\\([ 	]*GLOB[ 	]+" OR
		WT_CMAKE_CONTENT MATCHES "(^|[ 	])-s([ 	]|$)" OR
		WT_CMAKE_CONTENT MATCHES "(/home/mydeps|MyX64Deps|MyDepends12)")
		list(APPEND WT_CMAKE_HYGIENE_VIOLATIONS "${WT_CMAKE_LIST_RELATIVE}")
	endif()
endforeach()

if(WT_DIRECTORY_STATE_VIOLATIONS)
	list(JOIN WT_DIRECTORY_STATE_VIOLATIONS ", " WT_DIRECTORY_STATE_TEXT)
	message(FATAL_ERROR "Directory-scoped dependency state remains in: ${WT_DIRECTORY_STATE_TEXT}")
endif()

if(WT_CMAKE_HYGIENE_VIOLATIONS)
	list(JOIN WT_CMAKE_HYGIENE_VIOLATIONS ", " WT_CMAKE_HYGIENE_TEXT)
	message(FATAL_ERROR "Legacy output, source discovery, strip, or host paths remain in: ${WT_CMAKE_HYGIENE_TEXT}")
endif()

file(GLOB_RECURSE WT_PRODUCTION_SOURCES
	"${WT_SOURCE_DIR}/*.c"
	"${WT_SOURCE_DIR}/*.cc"
	"${WT_SOURCE_DIR}/*.cpp"
	"${WT_SOURCE_DIR}/*.h"
	"${WT_SOURCE_DIR}/*.hpp"
)
set(WT_SOURCE_DEPENDENCY_VIOLATIONS "")
set(WT_HEADER_NAMESPACE_VIOLATIONS "")
foreach(WT_SOURCE_FILE IN LISTS WT_PRODUCTION_SOURCES)
	file(RELATIVE_PATH WT_SOURCE_FILE_RELATIVE "${WT_SOURCE_DIR}" "${WT_SOURCE_FILE}")
	if(WT_SOURCE_FILE_RELATIVE MATCHES "^(API|out)/")
		continue()
	endif()
	file(READ "${WT_SOURCE_FILE}" WT_SOURCE_CONTENT)
	if(WT_SOURCE_CONTENT MATCHES "#[ 	]*include[ 	]*[<\"][^>\"]*API/" OR
		WT_SOURCE_CONTENT MATCHES "#[ 	]*pragma[ 	]+comment[ 	]*\\([ 	]*lib")
		list(APPEND WT_SOURCE_DEPENDENCY_VIOLATIONS "${WT_SOURCE_FILE_RELATIVE}")
	endif()
	if(WT_SOURCE_FILE_RELATIVE MATCHES "\\.(h|hpp)$" AND
		WT_SOURCE_CONTENT MATCHES "(^|\n)[ \t]*using[ \t]+namespace[ \t]+std[ \t]*;")
		list(APPEND WT_HEADER_NAMESPACE_VIOLATIONS "${WT_SOURCE_FILE_RELATIVE}")
	endif()
endforeach()

if(WT_SOURCE_DEPENDENCY_VIOLATIONS)
	list(JOIN WT_SOURCE_DEPENDENCY_VIOLATIONS ", " WT_SOURCE_DEPENDENCY_TEXT)
	message(FATAL_ERROR "Source-level SDK/library dependencies remain in: ${WT_SOURCE_DEPENDENCY_TEXT}")
endif()

if(WT_HEADER_NAMESPACE_VIOLATIONS)
	list(JOIN WT_HEADER_NAMESPACE_VIOLATIONS ", " WT_HEADER_NAMESPACE_TEXT)
	message(FATAL_ERROR "Headers leak 'using namespace std' in: ${WT_HEADER_NAMESPACE_TEXT}")
endif()
