
#1. 确定CMake的最低版本需求
CMAKE_MINIMUM_REQUIRED(VERSION 3.20)

#2. 确定工程名
PROJECT(TestPorter LANGUAGES CXX)


#7. 添加源码
SET(SRCS
	main.cpp
)

SET(LIBS
	WtPorter
)


ADD_EXECUTABLE(TestPorter ${SRCS})
TARGET_LINK_LIBRARIES(TestPorter PRIVATE WT::fmt WT::Boost)
TARGET_LINK_LIBRARIES(TestPorter PRIVATE ${LIBS})

IF (MSVC)
ELSE()
	SET_TARGET_PROPERTIES(TestPorter PROPERTIES
        BUILD_RPATH_USE_ORIGIN ON)
ENDIF ()
