#1. 确定CMake的最低版本需求
CMAKE_MINIMUM_REQUIRED(VERSION 3.20)

#2. 确定工程名
PROJECT(WtDtPorter LANGUAGES CXX)

SET(LIBRARY_OUTPUT_PATH ${CMAKE_BINARY_DIR}/build_${PLATFORM}/${CMAKE_BUILD_TYPE}/bin/WtDtPorter)

#7. 添加源码
file(GLOB SRCS *.cpp)
file(GLOB HDRS *.h)

IF(MSVC)
	list (APPEND SRCS ../Common/mdump.cpp)
ENDIF()

INCLUDE_DIRECTORIES(${INCS})
LINK_DIRECTORIES(${LNKS})
ADD_LIBRARY(WtDtPorter SHARED ${SRCS} ${HDRS})

SET(LIBS
	WtDtCore
	WTSTools
	WTSUtils
	)
IF(MSVC)
ELSE(GNUCC)
	LIST(APPEND LIBS
		${WT_DL_LIB}
		${WT_THREAD_LIB}
		boost_filesystem
		boost_thread
		${FS_LIB}
		)
	IF(WIN32)
		LIST(APPEND LIBS
			ws2_32 iconv
		)
	ENDIF()
ENDIF()

TARGET_LINK_LIBRARIES(WtDtPorter ${LIBS})
IF (MSVC)
ELSE (GNUCC)
	SET_TARGET_PROPERTIES(WtDtPorter PROPERTIES
		CXX_VISIBILITY_PRESET hidden
		VISIBILITY_INLINES_HIDDEN 1
        LINK_FLAGS_RELEASE -s)
ENDIF ()

file(MAKE_DIRECTORY ${LIBRARY_OUTPUT_PATH}/parsers/)
SET(WT_DT_PORTER_POST_BUILD_DEPENDS
	ParserXTP
	ParserFemas
	WtDataStorage
	WtDataStorageAD
)
SET(WT_DT_PORTER_POST_BUILD_COMMANDS )

IF(TARGET ParserCTP)
	LIST(APPEND WT_DT_PORTER_POST_BUILD_DEPENDS ParserCTP)
	LIST(APPEND WT_DT_PORTER_POST_BUILD_COMMANDS
		COMMAND ${CMAKE_COMMAND} -E
		copy ${CMAKE_BINARY_DIR}/build_${PLATFORM}/${CMAKE_BUILD_TYPE}/bin/${PREFIX}ParserCTP${SUFFIX} ${LIBRARY_OUTPUT_PATH}/parsers/
	)
ENDIF()

LIST(APPEND WT_DT_PORTER_POST_BUILD_COMMANDS
		COMMAND ${CMAKE_COMMAND} -E
		copy ${CMAKE_BINARY_DIR}/build_${PLATFORM}/${CMAKE_BUILD_TYPE}/bin/${PREFIX}ParserXTP${SUFFIX} ${LIBRARY_OUTPUT_PATH}/parsers/

		COMMAND ${CMAKE_COMMAND} -E
		copy ${CMAKE_BINARY_DIR}/build_${PLATFORM}/${CMAKE_BUILD_TYPE}/bin/${PREFIX}ParserFemas${SUFFIX} ${LIBRARY_OUTPUT_PATH}/parsers/
)

IF(TARGET ParserCTPMini)
	LIST(APPEND WT_DT_PORTER_POST_BUILD_DEPENDS ParserCTPMini)
	LIST(APPEND WT_DT_PORTER_POST_BUILD_COMMANDS
		COMMAND ${CMAKE_COMMAND} -E
		copy ${CMAKE_BINARY_DIR}/build_${PLATFORM}/${CMAKE_BUILD_TYPE}/bin/${PREFIX}ParserCTPMini${SUFFIX} ${LIBRARY_OUTPUT_PATH}/parsers/
	)
ENDIF()

IF(TARGET ParserCTPOpt)
	LIST(APPEND WT_DT_PORTER_POST_BUILD_DEPENDS ParserCTPOpt)
	LIST(APPEND WT_DT_PORTER_POST_BUILD_COMMANDS
		COMMAND ${CMAKE_COMMAND} -E
		copy ${CMAKE_BINARY_DIR}/build_${PLATFORM}/${CMAKE_BUILD_TYPE}/bin/${PREFIX}ParserCTPOpt${SUFFIX} ${LIBRARY_OUTPUT_PATH}/parsers/
	)
ENDIF()

LIST(APPEND WT_DT_PORTER_POST_BUILD_COMMANDS
		COMMAND ${CMAKE_COMMAND} -E
		copy ${CMAKE_BINARY_DIR}/build_${PLATFORM}/${CMAKE_BUILD_TYPE}/bin/${PREFIX}WtDataStorage${SUFFIX} ${LIBRARY_OUTPUT_PATH}/

		COMMAND ${CMAKE_COMMAND} -E
	copy ${CMAKE_BINARY_DIR}/build_${PLATFORM}/${CMAKE_BUILD_TYPE}/bin/${PREFIX}WtDataStorageAD${SUFFIX} ${LIBRARY_OUTPUT_PATH}/
)

add_dependencies(WtDtPorter ${WT_DT_PORTER_POST_BUILD_DEPENDS})
add_custom_command(TARGET WtDtPorter POST_BUILD
		${WT_DT_PORTER_POST_BUILD_COMMANDS}
		COMMENT "depends modules copied")
