
#1. 确定CMake的最低版本需求
CMAKE_MINIMUM_REQUIRED(VERSION 3.20)

#2. 确定工程名
PROJECT(TraderXTP LANGUAGES CXX)

SET(SRC  
	${PROJECT_SOURCE_DIR}/TraderXTP.cpp
	${PROJECT_SOURCE_DIR}/TraderXTP.h	
)


ADD_LIBRARY(TraderXTP SHARED ${SRC})
TARGET_LINK_LIBRARIES(TraderXTP PRIVATE WT::fmt PUBLIC WT::Vendor::XTP)

IF(MSVC)
	SET(LIBS
		ws2_32
		)
ELSE()
	IF(WIN32)
		SET(LIBS
			WT::Platform
			WT::BoostThread
			${FS_LIB}
			ws2_32
			)
	ELSE(UNIX)
		SET(LIBS
			WT::Platform
			WT::BoostThread
			${FS_LIB}
			)
	ENDIF()
ENDIF()
TARGET_LINK_LIBRARIES(TraderXTP PUBLIC ${LIBS})

IF (MSVC)
ELSE()
	SET_TARGET_PROPERTIES(TraderXTP PROPERTIES
		CXX_VISIBILITY_PRESET hidden
		C_VISIBILITY_PRESET hidden
		VISIBILITY_INLINES_HIDDEN 1
        BUILD_RPATH_USE_ORIGIN ON)
ENDIF ()

