function(WT_SETUP_PLATFORM_DEPENDENCY)
	if(TARGET WT::Platform)
		message(FATAL_ERROR "WT_SETUP_PLATFORM_DEPENDENCY must be called at most once")
	endif()

	find_package(Threads REQUIRED)
	add_library(WT_PLATFORM INTERFACE)
	add_library(WT::Platform ALIAS WT_PLATFORM)
	target_link_libraries(WT_PLATFORM INTERFACE Threads::Threads)
	if(CMAKE_DL_LIBS)
		target_link_libraries(WT_PLATFORM INTERFACE ${CMAKE_DL_LIBS})
	endif()
endfunction()

function(WT_SETUP_HEADER_DEPENDENCIES)
	if(TARGET WT::fmt OR TARGET WT::RapidJSON)
		message(FATAL_ERROR "WT_SETUP_HEADER_DEPENDENCIES must be called exactly once")
	endif()

	add_library(WT_FMT INTERFACE)
	add_library(WT::fmt ALIAS WT_FMT)
	find_package(fmt CONFIG QUIET)
	if(TARGET fmt::fmt-header-only)
		target_link_libraries(WT_FMT INTERFACE fmt::fmt-header-only)
		target_compile_definitions(WT_FMT INTERFACE WT_USE_STANDALONE_FMT FMT_HEADER_ONLY)
		message(STATUS "Using fmt package target fmt::fmt-header-only")
	elseif(TARGET fmt::fmt)
		target_link_libraries(WT_FMT INTERFACE fmt::fmt)
		target_compile_definitions(WT_FMT INTERFACE WT_USE_STANDALONE_FMT)
		message(STATUS "Using fmt package target fmt::fmt")
	else()
		set(WT_FMT_SEARCH_PATHS ${WT_FMT_INCLUDE_PATHS})
		if(WT_DEPS_ROOT)
			list(PREPEND WT_FMT_SEARCH_PATHS "${WT_DEPS_ROOT}/include")
		endif()
		find_path(WT_FMT_INCLUDE_DIR NAMES fmt/format.h PATHS ${WT_FMT_SEARCH_PATHS})
		find_path(WT_SPDLOG_FMT_SHIM_INCLUDE_DIR NAMES spdlog/fmt/fmt.h PATHS ${WT_FMT_SEARCH_PATHS})
		if(WT_FMT_INCLUDE_DIR)
			target_include_directories(WT_FMT SYSTEM INTERFACE "${WT_FMT_INCLUDE_DIR}")
			target_compile_definitions(WT_FMT INTERFACE WT_USE_STANDALONE_FMT FMT_HEADER_ONLY)
			message(STATUS "Using standalone fmt headers at ${WT_FMT_INCLUDE_DIR}")
		elseif(WT_SPDLOG_FMT_SHIM_INCLUDE_DIR)
			target_include_directories(WT_FMT SYSTEM INTERFACE "${WT_SPDLOG_FMT_SHIM_INCLUDE_DIR}")
			target_compile_definitions(WT_FMT INTERFACE WT_USE_SPDLOG_FMT_SHIM FMT_HEADER_ONLY)
			message(STATUS "Using spdlog fmt shim headers at ${WT_SPDLOG_FMT_SHIM_INCLUDE_DIR}")
		else()
			message(FATAL_ERROR "Could not find fmt headers. Set WT_DEPS_ROOT, provide fmt_DIR/CMAKE_PREFIX_PATH, or install fmt/spdlog headers")
		endif()
	endif()

	add_library(WT_RAPIDJSON INTERFACE)
	add_library(WT::RapidJSON ALIAS WT_RAPIDJSON)
	find_package(RapidJSON CONFIG QUIET)
	if(TARGET RapidJSON::RapidJSON)
		target_link_libraries(WT_RAPIDJSON INTERFACE RapidJSON::RapidJSON)
		message(STATUS "Using RapidJSON package target RapidJSON::RapidJSON")
	else()
		set(WT_RAPIDJSON_SEARCH_PATHS ${WT_RAPIDJSON_INCLUDE_PATHS})
		if(WT_DEPS_ROOT)
			list(PREPEND WT_RAPIDJSON_SEARCH_PATHS "${WT_DEPS_ROOT}/include")
		endif()
		find_path(WT_RAPIDJSON_INCLUDE_DIR NAMES rapidjson/document.h PATHS ${WT_RAPIDJSON_SEARCH_PATHS})
		if(NOT WT_RAPIDJSON_INCLUDE_DIR)
			message(FATAL_ERROR "Could not find RapidJSON headers. Set WT_DEPS_ROOT, provide RapidJSON_DIR/CMAKE_PREFIX_PATH, or install RapidJSON")
		endif()
		target_include_directories(WT_RAPIDJSON SYSTEM INTERFACE "${WT_RAPIDJSON_INCLUDE_DIR}")
		message(STATUS "Using RapidJSON headers at ${WT_RAPIDJSON_INCLUDE_DIR}")
	endif()
endfunction()

function(WT_SETUP_BOOST_DEPENDENCY)
	if(TARGET WT::Boost)
		message(FATAL_ERROR "WT_SETUP_BOOST_DEPENDENCY must be called exactly once")
	endif()

	set(WT_BOOST_UPSTREAM_TARGETS
		Boost::filesystem
		Boost::thread
		Boost::chrono
		Boost::atomic
	)
	set(WT_BOOST_TARGETS_READY TRUE)
	foreach(WT_BOOST_UPSTREAM_TARGET IN LISTS WT_BOOST_UPSTREAM_TARGETS)
		if(NOT TARGET ${WT_BOOST_UPSTREAM_TARGET})
			set(WT_BOOST_TARGETS_READY FALSE)
		endif()
	endforeach()

	set(WT_BOOST_SELECTED_PREFIXES "")
	if(WT_DEPS_ROOT)
		set(WT_BOOST_SELECTED_PREFIXES "${WT_DEPS_ROOT}")
	elseif(CMAKE_PREFIX_PATH)
		set(WT_BOOST_SELECTED_PREFIXES ${CMAKE_PREFIX_PATH})
	elseif(WT_BOOST_PREFIX_HINTS)
		set(WT_BOOST_SELECTED_PREFIXES ${WT_BOOST_PREFIX_HINTS})
	endif()

	if(NOT WT_BOOST_TARGETS_READY)
		if(WT_BOOST_SELECTED_PREFIXES)
			find_package(Boost CONFIG QUIET COMPONENTS filesystem thread chrono atomic
				PATHS ${WT_BOOST_SELECTED_PREFIXES}
				NO_DEFAULT_PATH
			)
		else()
			find_package(Boost CONFIG QUIET COMPONENTS filesystem thread chrono atomic)
		endif()
	endif()

	set(WT_BOOST_TARGETS_READY TRUE)
	foreach(WT_BOOST_UPSTREAM_TARGET IN LISTS WT_BOOST_UPSTREAM_TARGETS)
		if(NOT TARGET ${WT_BOOST_UPSTREAM_TARGET})
			set(WT_BOOST_TARGETS_READY FALSE)
		endif()
	endforeach()
	if(NOT WT_BOOST_TARGETS_READY)
		set(Boost_NO_BOOST_CMAKE ON)
		set(Boost_NO_WARN_NEW_VERSIONS ON)
		if(WT_BOOST_SELECTED_PREFIXES)
			list(GET WT_BOOST_SELECTED_PREFIXES 0 WT_BOOST_FALLBACK_ROOT)
			set(Boost_ROOT "${WT_BOOST_FALLBACK_ROOT}")
			set(BOOST_ROOT "${WT_BOOST_FALLBACK_ROOT}")
			set(BOOST_INCLUDEDIR "${WT_BOOST_FALLBACK_ROOT}/include")
			if(IS_DIRECTORY "${WT_BOOST_FALLBACK_ROOT}/lib")
				set(BOOST_LIBRARYDIR "${WT_BOOST_FALLBACK_ROOT}/lib")
			elseif(IS_DIRECTORY "${WT_BOOST_FALLBACK_ROOT}/lib64")
				set(BOOST_LIBRARYDIR "${WT_BOOST_FALLBACK_ROOT}/lib64")
			endif()
		endif()
		find_package(Boost REQUIRED COMPONENTS filesystem thread chrono atomic)
	endif()

	if(TARGET Boost::headers)
		set(WT_BOOST_HEADERS_TARGET Boost::headers)
	elseif(TARGET Boost::boost)
		set(WT_BOOST_HEADERS_TARGET Boost::boost)
	else()
		message(FATAL_ERROR "Boost discovery did not provide Boost::headers or Boost::boost")
	endif()

	add_library(WT_BOOST INTERFACE)
	add_library(WT::Boost ALIAS WT_BOOST)
	target_link_libraries(WT_BOOST INTERFACE ${WT_BOOST_HEADERS_TARGET})

	foreach(WT_BOOST_COMPONENT IN ITEMS Filesystem Thread Chrono Atomic)
		string(TOUPPER "${WT_BOOST_COMPONENT}" WT_BOOST_COMPONENT_UPPER)
		string(TOLOWER "${WT_BOOST_COMPONENT}" WT_BOOST_COMPONENT_LOWER)
		add_library(WT_BOOST_${WT_BOOST_COMPONENT_UPPER} INTERFACE)
		add_library(WT::Boost${WT_BOOST_COMPONENT} ALIAS WT_BOOST_${WT_BOOST_COMPONENT_UPPER})
		target_link_libraries(WT_BOOST_${WT_BOOST_COMPONENT_UPPER} INTERFACE
			WT::Boost
			Boost::${WT_BOOST_COMPONENT_LOWER}
		)
	endforeach()
	message(STATUS "Using Boost ${Boost_VERSION_STRING} through target providers")
endfunction()

function(WT_SETUP_NANOMSG_DEPENDENCY)
	if(TARGET WT::Nanomsg)
		message(FATAL_ERROR "WT_SETUP_NANOMSG_DEPENDENCY must be called exactly once")
	endif()

	find_package(nanomsg CONFIG QUIET)
	if(TARGET nanomsg)
		set(WT_NANOMSG_TARGET nanomsg)
	elseif(TARGET nanomsg::nanomsg)
		set(WT_NANOMSG_TARGET nanomsg::nanomsg)
	elseif(TARGET Nanomsg::nanomsg)
		set(WT_NANOMSG_TARGET Nanomsg::nanomsg)
	endif()
	if(WT_NANOMSG_TARGET)
		add_library(WT_NANOMSG INTERFACE)
		add_library(WT::Nanomsg ALIAS WT_NANOMSG)
		target_link_libraries(WT_NANOMSG INTERFACE ${WT_NANOMSG_TARGET})
		message(STATUS "Using nanomsg package target ${WT_NANOMSG_TARGET}")
		return()
	endif()

	set(WT_NANOMSG_INCLUDE_HINTS ${WT_NANOMSG_INCLUDE_PATHS})
	set(WT_NANOMSG_LIBRARY_HINTS ${WT_NANOMSG_LIBRARY_PATHS})
	if(WT_DEPS_ROOT)
		list(PREPEND WT_NANOMSG_INCLUDE_HINTS "${WT_DEPS_ROOT}/include")
		list(PREPEND WT_NANOMSG_LIBRARY_HINTS "${WT_DEPS_ROOT}/lib" "${WT_DEPS_ROOT}/lib64")
	endif()
	find_path(WT_NANOMSG_INCLUDE_DIR NAMES nanomsg/nn.h HINTS ${WT_NANOMSG_INCLUDE_HINTS})
	find_library(WT_NANOMSG_LIB NAMES nanomsg HINTS ${WT_NANOMSG_LIBRARY_HINTS})
	if(NOT WT_NANOMSG_INCLUDE_DIR OR NOT WT_NANOMSG_LIB)
		message(FATAL_ERROR
			"Could not find nanomsg headers and library. Set WT_DEPS_ROOT, provide "
			"nanomsg_DIR/CMAKE_PREFIX_PATH, or install nanomsg"
		)
	endif()

	add_library(WT_NANOMSG_LIBRARY UNKNOWN IMPORTED)
	set_target_properties(WT_NANOMSG_LIBRARY PROPERTIES IMPORTED_LOCATION "${WT_NANOMSG_LIB}")
	add_library(WT_NANOMSG INTERFACE)
	add_library(WT::Nanomsg ALIAS WT_NANOMSG)
	target_include_directories(WT_NANOMSG SYSTEM INTERFACE "${WT_NANOMSG_INCLUDE_DIR}")
	target_link_libraries(WT_NANOMSG INTERFACE WT_NANOMSG_LIBRARY)
	message(STATUS "Using nanomsg library at ${WT_NANOMSG_LIB}")
	message(STATUS "Using nanomsg headers at ${WT_NANOMSG_INCLUDE_DIR}")
endfunction()

function(WT_SETUP_ZMQ_DEPENDENCY)
	if(TARGET WT::ZMQ)
		message(FATAL_ERROR "WT_SETUP_ZMQ_DEPENDENCY must be called at most once")
	endif()

	find_package(cppzmq CONFIG QUIET)
	if(TARGET cppzmq)
		set(WT_CPPZMQ_TARGET cppzmq)
	elseif(TARGET cppzmq::cppzmq)
		set(WT_CPPZMQ_TARGET cppzmq::cppzmq)
	endif()
	if(WT_CPPZMQ_TARGET)
		add_library(WT_ZMQ INTERFACE)
		add_library(WT::ZMQ ALIAS WT_ZMQ)
		target_link_libraries(WT_ZMQ INTERFACE ${WT_CPPZMQ_TARGET})
		set(WT_ZMQ_MISSING "" PARENT_SCOPE)
		message(STATUS "Using cppzmq package target ${WT_CPPZMQ_TARGET}")
		return()
	endif()

	set(WT_ZMQ_INCLUDE_HINTS ${WT_ZMQ_INCLUDE_PATHS})
	set(WT_CPPZMQ_INCLUDE_HINTS ${WT_CPPZMQ_INCLUDE_PATHS})
	set(WT_ZMQ_LIBRARY_HINTS ${WT_ZMQ_LIBRARY_PATHS})
	if(WT_DEPS_ROOT)
		list(PREPEND WT_ZMQ_INCLUDE_HINTS "${WT_DEPS_ROOT}/include")
		list(PREPEND WT_CPPZMQ_INCLUDE_HINTS "${WT_DEPS_ROOT}/include")
		list(PREPEND WT_ZMQ_LIBRARY_HINTS "${WT_DEPS_ROOT}/lib" "${WT_DEPS_ROOT}/lib64")
	endif()

	find_path(WT_ZMQ_INCLUDE_DIR NAMES zmq.h HINTS ${WT_ZMQ_INCLUDE_HINTS})
	find_path(WT_CPPZMQ_INCLUDE_DIR NAMES zmq.hpp HINTS ${WT_CPPZMQ_INCLUDE_HINTS})
	find_library(WT_ZMQ_LIB NAMES zmq libzmq HINTS ${WT_ZMQ_LIBRARY_HINTS})

	set(WT_ZMQ_MISSING "")
	if(NOT WT_ZMQ_INCLUDE_DIR)
		list(APPEND WT_ZMQ_MISSING "zmq.h")
	endif()
	if(NOT WT_CPPZMQ_INCLUDE_DIR)
		list(APPEND WT_ZMQ_MISSING "zmq.hpp/cppzmq")
	endif()
	if(NOT WT_ZMQ_LIB)
		list(APPEND WT_ZMQ_MISSING "libzmq")
	endif()
	if(WT_ZMQ_MISSING)
		set(WT_ZMQ_MISSING "${WT_ZMQ_MISSING}" PARENT_SCOPE)
		return()
	endif()

	add_library(WT_ZMQ_LIBRARY UNKNOWN IMPORTED)
	set_target_properties(WT_ZMQ_LIBRARY PROPERTIES IMPORTED_LOCATION "${WT_ZMQ_LIB}")
	add_library(WT_ZMQ INTERFACE)
	add_library(WT::ZMQ ALIAS WT_ZMQ)
	target_include_directories(WT_ZMQ SYSTEM INTERFACE
		"${WT_ZMQ_INCLUDE_DIR}"
		"${WT_CPPZMQ_INCLUDE_DIR}"
	)
	target_link_libraries(WT_ZMQ INTERFACE WT_ZMQ_LIBRARY)
	set(WT_ZMQ_MISSING "" PARENT_SCOPE)
	message(STATUS "Using ZeroMQ library at ${WT_ZMQ_LIB}")
	message(STATUS "Using ZeroMQ headers at ${WT_ZMQ_INCLUDE_DIR} and ${WT_CPPZMQ_INCLUDE_DIR}")
endfunction()
