function(WT_CONFIGURE_WTRUNNER_INSTALL)
	include(GNUInstallDirs)
	if(POLICY CMP0207)
		cmake_policy(SET CMP0207 NEW)
	endif()
	if(NOT TARGET WtRunner)
		message(FATAL_ERROR "WT_CONFIGURE_WTRUNNER_INSTALL requires WtRunner")
	endif()

	option(WT_INSTALL_BUNDLED_VENDOR_RUNTIMES
		"Install repository-bundled vendor plugins/runtimes after redistribution approval"
		OFF
	)
	set(WT_INSTALL_ROOT "${CMAKE_INSTALL_BINDIR}/WtRunner")
	set(WT_INSTALL_ROOT_TARGETS
		WtRunner
		WtDataStorage
		WtDataStorageAD
		WtRiskMonFact
		WtMsgQue
	)
	set(WT_INSTALL_PARSER_TARGETS ParserUDP ParserShm ParserXeleSkt)
	set(WT_INSTALL_TRADER_TARGETS TraderMocker)
	set(WT_INSTALL_EXECUTER_TARGETS WtExeFact)
	set(WT_INSTALL_VENDOR_RUNTIME_ARTIFACTS "")
	set(WT_INSTALL_VENDOR_RUNTIME_NAMES "")
	set(WT_INSTALL_VENDOR_RUNTIME_SOURCES "")

	foreach(WT_OPTIONAL_PARSER_TARGET IN ITEMS ParserZMQ)
		if(TARGET ${WT_OPTIONAL_PARSER_TARGET})
			list(APPEND WT_INSTALL_PARSER_TARGETS ${WT_OPTIONAL_PARSER_TARGET})
		endif()
	endforeach()
	foreach(WT_OPTIONAL_TRADER_TARGET IN ITEMS TraderZMQ)
		if(TARGET ${WT_OPTIONAL_TRADER_TARGET})
			list(APPEND WT_INSTALL_TRADER_TARGETS ${WT_OPTIONAL_TRADER_TARGET})
		endif()
	endforeach()

	macro(WT_APPEND_VENDOR_COMPONENT WT_COMPONENT_KIND WT_COMPONENT_TARGET WT_RUNTIME_VARIABLE)
		if(TARGET ${WT_COMPONENT_TARGET})
			if("${WT_COMPONENT_KIND}" STREQUAL "PARSER")
				list(APPEND WT_INSTALL_PARSER_TARGETS ${WT_COMPONENT_TARGET})
			elseif("${WT_COMPONENT_KIND}" STREQUAL "TRADER")
				list(APPEND WT_INSTALL_TRADER_TARGETS ${WT_COMPONENT_TARGET})
			else()
				message(FATAL_ERROR "Unknown vendor component kind ${WT_COMPONENT_KIND}")
			endif()

			foreach(WT_VENDOR_RUNTIME IN LISTS ${WT_RUNTIME_VARIABLE})
				if(NOT EXISTS "${WT_VENDOR_RUNTIME}")
					message(FATAL_ERROR
						"Cannot package ${WT_COMPONENT_TARGET}: vendor runtime is missing: ${WT_VENDOR_RUNTIME}"
					)
				endif()
				get_filename_component(WT_VENDOR_RUNTIME_NAME "${WT_VENDOR_RUNTIME}" NAME)
				list(FIND WT_INSTALL_VENDOR_RUNTIME_NAMES "${WT_VENDOR_RUNTIME_NAME}" WT_VENDOR_RUNTIME_INDEX)
				if(WT_VENDOR_RUNTIME_INDEX EQUAL -1)
					list(APPEND WT_INSTALL_VENDOR_RUNTIME_NAMES "${WT_VENDOR_RUNTIME_NAME}")
					list(APPEND WT_INSTALL_VENDOR_RUNTIME_SOURCES "${WT_VENDOR_RUNTIME}")
					list(APPEND WT_INSTALL_VENDOR_RUNTIME_ARTIFACTS "${WT_VENDOR_RUNTIME}")
				else()
					list(GET WT_INSTALL_VENDOR_RUNTIME_SOURCES ${WT_VENDOR_RUNTIME_INDEX} WT_EXISTING_RUNTIME)
					file(SHA256 "${WT_EXISTING_RUNTIME}" WT_EXISTING_RUNTIME_HASH)
					file(SHA256 "${WT_VENDOR_RUNTIME}" WT_VENDOR_RUNTIME_HASH)
					if(NOT WT_EXISTING_RUNTIME_HASH STREQUAL WT_VENDOR_RUNTIME_HASH)
						message(FATAL_ERROR
							"Vendor runtime filename collision for ${WT_VENDOR_RUNTIME_NAME}: "
							"${WT_EXISTING_RUNTIME} and ${WT_VENDOR_RUNTIME} differ"
						)
					endif()
				endif()
			endforeach()
		endif()
	endmacro()

	if(WT_INSTALL_BUNDLED_VENDOR_RUNTIMES)
		set(WT_CTP_RUNTIME_ARTIFACTS "")
		foreach(WT_CTP_RUNTIME IN ITEMS "${WT_CTP_MD_LIBRARY_RESOLVED}" "${WT_CTP_TRADER_LIBRARY_RESOLVED}")
			if(WT_CTP_RUNTIME AND EXISTS "${WT_CTP_RUNTIME}")
				list(APPEND WT_CTP_RUNTIME_ARTIFACTS "${WT_CTP_RUNTIME}")
			endif()
		endforeach()
		if(WIN32 AND TARGET TraderCTP)
			foreach(WT_CTP_RUNTIME_BASE IN ITEMS thostmduserapi_se thosttraderapi_se)
				unset(WT_CTP_RUNTIME_FILE CACHE)
				find_file(WT_CTP_RUNTIME_FILE
					NAMES "${WT_CTP_RUNTIME_BASE}.dll"
					PATHS "${CTP_ROOT}/${WT_ARCH}" "${CTP_ROOT}/bin/${WT_ARCH}" "${CTP_ROOT}/bin"
					NO_DEFAULT_PATH
				)
				if(WT_CTP_RUNTIME_FILE)
					list(APPEND WT_CTP_RUNTIME_ARTIFACTS "${WT_CTP_RUNTIME_FILE}")
				endif()
			endforeach()
		endif()
		list(REMOVE_DUPLICATES WT_CTP_RUNTIME_ARTIFACTS)
		if((TARGET ParserCTP OR TARGET TraderCTP) AND NOT WT_CTP_RUNTIME_ARTIFACTS)
			message(FATAL_ERROR
				"WT_INSTALL_BUNDLED_VENDOR_RUNTIMES=ON requires CTP runtime artifacts for packaged CTP plugins"
			)
		endif()

		WT_APPEND_VENDOR_COMPONENT(PARSER ParserCTP WT_CTP_RUNTIME_ARTIFACTS)
		WT_APPEND_VENDOR_COMPONENT(TRADER TraderCTP WT_CTP_RUNTIME_ARTIFACTS)
		WT_APPEND_VENDOR_COMPONENT(PARSER ParserCTPMini WT_CTP_MINI_RUNTIME_ARTIFACTS)
		WT_APPEND_VENDOR_COMPONENT(TRADER TraderCTPMini WT_CTP_MINI_RUNTIME_ARTIFACTS)
		WT_APPEND_VENDOR_COMPONENT(PARSER ParserCTPOpt WT_CTP_OPT_RUNTIME_ARTIFACTS)
		WT_APPEND_VENDOR_COMPONENT(TRADER TraderCTPOpt WT_CTP_OPT_RUNTIME_ARTIFACTS)
		WT_APPEND_VENDOR_COMPONENT(PARSER ParserFemas WT_FEMAS_RUNTIME_ARTIFACTS)
		WT_APPEND_VENDOR_COMPONENT(TRADER TraderFemas WT_FEMAS_RUNTIME_ARTIFACTS)
		WT_APPEND_VENDOR_COMPONENT(PARSER ParserXTP WT_XTP_RUNTIME_ARTIFACTS)
		WT_APPEND_VENDOR_COMPONENT(TRADER TraderXTP WT_XTP_RUNTIME_ARTIFACTS)
		WT_APPEND_VENDOR_COMPONENT(PARSER ParserYD WT_YD_RUNTIME_ARTIFACTS)
		WT_APPEND_VENDOR_COMPONENT(TRADER TraderYD WT_YD_RUNTIME_ARTIFACTS)
		WT_APPEND_VENDOR_COMPONENT(PARSER ParserOES WT_OES_RUNTIME_ARTIFACTS)
		WT_APPEND_VENDOR_COMPONENT(TRADER TraderOES WT_OES_RUNTIME_ARTIFACTS)
		WT_APPEND_VENDOR_COMPONENT(TRADER TraderATP WT_ATP_RUNTIME_ARTIFACTS)
		WT_APPEND_VENDOR_COMPONENT(PARSER ParserHuaX WT_HUAX_PARSER_RUNTIME_ARTIFACTS)
		WT_APPEND_VENDOR_COMPONENT(TRADER TraderHuaX WT_HUAX_TRADER_RUNTIME_ARTIFACTS)
		WT_APPEND_VENDOR_COMPONENT(TRADER TraderXTPXAlgo WT_XTP_XALGO_RUNTIME_ARTIFACTS)
		WT_APPEND_VENDOR_COMPONENT(TRADER TraderDD WT_DD_RUNTIME_ARTIFACTS)
		WT_APPEND_VENDOR_COMPONENT(TRADER TraderHTS WT_HTS_RUNTIME_ARTIFACTS)
	endif()

	if(APPLE)
		set(WT_INSTALL_ROOT_RPATH "@loader_path")
		set(WT_INSTALL_NESTED_RPATH "@loader_path/..")
	elseif(UNIX)
		set(WT_INSTALL_ROOT_RPATH "$ORIGIN")
		set(WT_INSTALL_NESTED_RPATH "$ORIGIN/..")
	else()
		set(WT_INSTALL_ROOT_RPATH "")
		set(WT_INSTALL_NESTED_RPATH "")
	endif()
	set_target_properties(${WT_INSTALL_ROOT_TARGETS} PROPERTIES
		BUILD_RPATH_USE_ORIGIN ON
		INSTALL_RPATH "${WT_INSTALL_ROOT_RPATH}"
	)
	set(WT_INSTALL_NESTED_TARGETS
		${WT_INSTALL_PARSER_TARGETS}
		${WT_INSTALL_TRADER_TARGETS}
		${WT_INSTALL_EXECUTER_TARGETS}
	)
	set_target_properties(${WT_INSTALL_NESTED_TARGETS} PROPERTIES
		BUILD_RPATH_USE_ORIGIN ON
		INSTALL_RPATH "${WT_INSTALL_NESTED_RPATH}"
	)

	install(TARGETS ${WT_INSTALL_ROOT_TARGETS}
		RUNTIME_DEPENDENCY_SET WonderTraderRuntimeDependencies
		RUNTIME DESTINATION "${WT_INSTALL_ROOT}"
		LIBRARY DESTINATION "${WT_INSTALL_ROOT}"
	)
	install(TARGETS ${WT_INSTALL_PARSER_TARGETS}
		RUNTIME_DEPENDENCY_SET WonderTraderRuntimeDependencies
		RUNTIME DESTINATION "${WT_INSTALL_ROOT}/parsers"
		LIBRARY DESTINATION "${WT_INSTALL_ROOT}/parsers"
	)
	install(TARGETS ${WT_INSTALL_TRADER_TARGETS}
		RUNTIME_DEPENDENCY_SET WonderTraderRuntimeDependencies
		RUNTIME DESTINATION "${WT_INSTALL_ROOT}/traders"
		LIBRARY DESTINATION "${WT_INSTALL_ROOT}/traders"
	)
	install(TARGETS ${WT_INSTALL_EXECUTER_TARGETS}
		RUNTIME_DEPENDENCY_SET WonderTraderRuntimeDependencies
		RUNTIME DESTINATION "${WT_INSTALL_ROOT}/executer"
		LIBRARY DESTINATION "${WT_INSTALL_ROOT}/executer"
	)

	set(WT_RUNTIME_PRE_EXCLUDES "^$")
	if(WIN32)
		# API-set DLLs are virtual OS contracts. The MSVC/UCRT DLLs are an
		# operating-system or Visual C++ Redistributable prerequisite and were
		# already excluded after resolution through System32; excluding their
		# names up front also avoids false unresolved-dependency reports.
		set(WT_RUNTIME_PRE_EXCLUDES
			"[Aa][Pp][Ii]-[Mm][Ss]-[Ww][Ii][Nn]-.*\\.dll"
			"[Ee][Xx][Tt]-[Mm][Ss]-[Ww][Ii][Nn]-.*\\.dll"
			"[Mm][Ss][Vv][Cc][Pp].*\\.dll"
			"[Uu][Cc][Rr][Tt][Bb][Aa][Ss][Ee]\\.dll"
			"[Vv][Cc][Rr][Uu][Nn][Tt][Ii][Mm][Ee].*\\.dll"
		)
		set(WT_RUNTIME_POST_EXCLUDES
			".*[Ww][Ii][Nn][Dd][Oo][Ww][Ss][/\\\\][Ss][Yy][Ss][Tt][Ee][Mm]32.*"
		)
	elseif(APPLE)
		set(WT_RUNTIME_POST_EXCLUDES "^/System/Library/.*" "^/usr/lib/.*")
	else()
		set(WT_RUNTIME_POST_EXCLUDES "^/lib/.*" "^/lib64/.*" "^/usr/lib/.*")
	endif()
	install(RUNTIME_DEPENDENCY_SET WonderTraderRuntimeDependencies
		DESTINATION "${WT_INSTALL_ROOT}"
		PRE_EXCLUDE_REGEXES ${WT_RUNTIME_PRE_EXCLUDES}
		POST_EXCLUDE_REGEXES ${WT_RUNTIME_POST_EXCLUDES}
		DIRECTORIES ${WT_DEP_LIBRARY_PATHS}
	)

	if(WT_INSTALL_VENDOR_RUNTIME_ARTIFACTS)
		install(FILES ${WT_INSTALL_VENDOR_RUNTIME_ARTIFACTS}
			DESTINATION "${WT_INSTALL_ROOT}"
		)
	endif()
endfunction()
