
#1. 确定CMake的最低版本需求
CMAKE_MINIMUM_REQUIRED(VERSION 3.20)

#2. 确定工程名
PROJECT(WtSelStraFact LANGUAGES CXX)

#7. 添加源码
SET(SRCS
	WtSelStraFact.cpp
	WtStraDtSel.cpp
)
SET(HDRS
	WtSelStraFact.h
	WtStraDtSel.h
)


ADD_LIBRARY(WtSelStraFact SHARED ${SRCS} ${HDRS})
TARGET_LINK_LIBRARIES(WtSelStraFact PRIVATE WT::fmt WT::Boost)

SET(LIBS
	${FS_LIB}
	WT::Platform
)

IF (WIN32)
ELSE (UNIX)
	TARGET_LINK_LIBRARIES(WtSelStraFact PUBLIC ${LIBS})
	SET_TARGET_PROPERTIES(WtSelStraFact PROPERTIES
		CXX_VISIBILITY_PRESET hidden
		C_VISIBILITY_PRESET hidden
		VISIBILITY_INLINES_HIDDEN 1
        BUILD_RPATH_USE_ORIGIN ON)
ENDIF ()

