if(NOT DEFINED WT_TEST_EXECUTABLE OR WT_TEST_EXECUTABLE STREQUAL "")
	message(FATAL_ERROR "WT_TEST_EXECUTABLE is required")
endif()

if(NOT EXISTS "${WT_TEST_EXECUTABLE}")
	message(FATAL_ERROR "Test executable does not exist: ${WT_TEST_EXECUTABLE}")
endif()

if(NOT DEFINED WT_TEST_SANDBOX_ROOT OR WT_TEST_SANDBOX_ROOT STREQUAL "")
	message(FATAL_ERROR "WT_TEST_SANDBOX_ROOT is required")
endif()

string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef WT_TEST_SANDBOX_ID)
set(WT_TEST_SANDBOX "${WT_TEST_SANDBOX_ROOT}/${WT_TEST_SANDBOX_ID}")

file(MAKE_DIRECTORY "${WT_TEST_SANDBOX}")

execute_process(
	COMMAND "${WT_TEST_EXECUTABLE}"
	WORKING_DIRECTORY "${WT_TEST_SANDBOX}"
	RESULT_VARIABLE WT_TEST_RESULT
)

file(REMOVE_RECURSE "${WT_TEST_SANDBOX}")

if(NOT "${WT_TEST_RESULT}" STREQUAL "0")
	message(FATAL_ERROR "Test process failed with result: ${WT_TEST_RESULT}")
endif()
