#1. 确定CMake的最低版本需求
cmake_minimum_required(VERSION 3.20)

#2. 确定工程名
PROJECT(ParserZMQ LANGUAGES CXX)

SET(SRC
	${PROJECT_SOURCE_DIR}/ParserZMQ.cpp
	${PROJECT_SOURCE_DIR}/ParserZMQ.h
)

SET(LIBRARY_OUTPUT_PATH ${CMAKE_BINARY_DIR}/build_${PLATFORM}/${CMAKE_BUILD_TYPE}/bin)

ADD_LIBRARY(ParserZMQ SHARED ${SRC})
TARGET_LINK_LIBRARIES(ParserZMQ
	PUBLIC WT::ZMQ
	PRIVATE WT::fmt WT::RapidJSON WT::Platform
)

IF (MSVC)
ELSE (GNUCC)
	SET_TARGET_PROPERTIES(ParserZMQ PROPERTIES
		CXX_VISIBILITY_PRESET hidden
		C_VISIBILITY_PRESET hidden
		VISIBILITY_INLINES_HIDDEN 1
        LINK_FLAGS_RELEASE -s)
ENDIF ()
