#1. 确定CMake的最低版本需求
CMAKE_MINIMUM_REQUIRED(VERSION 3.20)

#2. 确定工程名
PROJECT(WtShareHelper LANGUAGES CXX)

#7. 添加源码
SET(SRCS
	ShareBlocks.cpp
	WtShareHelper.cpp
)
SET(HDRS
	ShareBlocks.h
	WtShareHelper.h
)


ADD_LIBRARY(WtShareHelper SHARED ${SRCS} ${HDRS})
TARGET_LINK_LIBRARIES(WtShareHelper PUBLIC WT::fmt)

SET(LIBS
	${FS_LIB}
	WT::Platform
)

IF (WIN32)
ELSE (UNIX)
	TARGET_LINK_LIBRARIES(WtShareHelper PUBLIC ${LIBS})
	SET_TARGET_PROPERTIES(WtShareHelper PROPERTIES
		CXX_VISIBILITY_PRESET hidden
		C_VISIBILITY_PRESET hidden
		VISIBILITY_INLINES_HIDDEN 1
        BUILD_RPATH_USE_ORIGIN ON)
ENDIF ()

