#1. 确定CMake的最低版本需求
CMAKE_MINIMUM_REQUIRED(VERSION 3.20)

#2. 确定工程名
PROJECT(WtHftStraFact LANGUAGES CXX)

#7. 添加源码
SET(SRCS
	WtHftStraDemo.cpp
	WtHftStraFact.cpp
)
SET(HDRS
	WtHftStraDemo.h
	WtHftStraFact.h
)


ADD_LIBRARY(WtHftStraFact SHARED ${SRCS} ${HDRS})
TARGET_LINK_LIBRARIES(WtHftStraFact PRIVATE WT::fmt)

SET(LIBS
	${FS_LIB}
	WT::Platform
)

IF (WIN32)
ELSE (UNIX)
	TARGET_LINK_LIBRARIES(WtHftStraFact PUBLIC ${LIBS})
	SET_TARGET_PROPERTIES(WtHftStraFact PROPERTIES
		CXX_VISIBILITY_PRESET hidden
		C_VISIBILITY_PRESET hidden
		VISIBILITY_INLINES_HIDDEN 1
        BUILD_RPATH_USE_ORIGIN ON)
ENDIF ()

