#1. 确定CMake的最低版本需求
CMAKE_MINIMUM_REQUIRED(VERSION 3.20)

#2. 确定工程名
PROJECT(WtRunner LANGUAGES CXX)

SET(EXECUTABLE_OUTPUT_PATH ${CMAKE_BINARY_DIR}/build_${PLATFORM}/${CMAKE_BUILD_TYPE}/bin/WtRunner)

#7. 添加源码
file(GLOB SRCS *.cpp)
file(GLOB HDRS *.h)

IF(MSVC)
	list (APPEND SRCS ../Common/mdump.cpp)
ENDIF()

INCLUDE_DIRECTORIES(${INCS})
LINK_DIRECTORIES(${LNKS})

SET(LIBS
	WtCore
	WTSTools
	WTSUtils
	)

IF (MSVC)
	LIST(APPEND LIBS ws2_32)
ELSE(GNUCC)
	LIST(APPEND LIBS
		${WT_DL_LIB}
		${WT_THREAD_LIB}
		boost_filesystem
		boost_thread
		${FS_LIB})
	IF(WIN32)
		LIST(APPEND LIBS
			ws2_32 iconv)
	ENDIF()
ENDIF()

ADD_EXECUTABLE(WtRunner ${SRCS} ${HDRS})
TARGET_LINK_LIBRARIES(WtRunner ${LIBS})

IF (MSVC)
ELSE (GNUCC)
	SET_TARGET_PROPERTIES(WtRunner PROPERTIES
        LINK_FLAGS_RELEASE -s)
ENDIF ()

file(MAKE_DIRECTORY ${EXECUTABLE_OUTPUT_PATH}/parsers/)
file(MAKE_DIRECTORY ${EXECUTABLE_OUTPUT_PATH}/traders/)
file(MAKE_DIRECTORY ${EXECUTABLE_OUTPUT_PATH}/executer/)

SET(WT_RUNNER_POST_BUILD_DEPENDS
	ParserUDP
	TraderXTP
	TraderMocker
	TraderFemas
	WtExeFact
	WtDataStorage
	WtDataStorageAD
	WtRiskMonFact
	WtMsgQue
)
SET(WT_RUNNER_POST_BUILD_COMMANDS
	COMMAND ${CMAKE_COMMAND} -E
	copy ${CMAKE_BINARY_DIR}/build_${PLATFORM}/${CMAKE_BUILD_TYPE}/bin/${PREFIX}ParserUDP${SUFFIX} ${EXECUTABLE_OUTPUT_PATH}/parsers/
)

IF(TARGET TraderCTP)
	LIST(APPEND WT_RUNNER_POST_BUILD_DEPENDS TraderCTP)
	LIST(APPEND WT_RUNNER_POST_BUILD_COMMANDS
	COMMAND ${CMAKE_COMMAND} -E
	copy ${CMAKE_BINARY_DIR}/build_${PLATFORM}/${CMAKE_BUILD_TYPE}/bin/${PREFIX}TraderCTP${SUFFIX} ${EXECUTABLE_OUTPUT_PATH}/traders/
	)
ENDIF()

LIST(APPEND WT_RUNNER_POST_BUILD_COMMANDS
	COMMAND ${CMAKE_COMMAND} -E
	copy ${CMAKE_BINARY_DIR}/build_${PLATFORM}/${CMAKE_BUILD_TYPE}/bin/${PREFIX}TraderXTP${SUFFIX} ${EXECUTABLE_OUTPUT_PATH}/traders/

	COMMAND ${CMAKE_COMMAND} -E
	copy ${CMAKE_BINARY_DIR}/build_${PLATFORM}/${CMAKE_BUILD_TYPE}/bin/${PREFIX}TraderMocker${SUFFIX} ${EXECUTABLE_OUTPUT_PATH}/traders/
)

IF(TARGET TraderCTPMini)
	LIST(APPEND WT_RUNNER_POST_BUILD_DEPENDS TraderCTPMini)
	LIST(APPEND WT_RUNNER_POST_BUILD_COMMANDS
	COMMAND ${CMAKE_COMMAND} -E
	copy ${CMAKE_BINARY_DIR}/build_${PLATFORM}/${CMAKE_BUILD_TYPE}/bin/${PREFIX}TraderCTPMini${SUFFIX} ${EXECUTABLE_OUTPUT_PATH}/traders/
	)
ENDIF()

IF(TARGET TraderCTPOpt)
	LIST(APPEND WT_RUNNER_POST_BUILD_DEPENDS TraderCTPOpt)
	LIST(APPEND WT_RUNNER_POST_BUILD_COMMANDS
	COMMAND ${CMAKE_COMMAND} -E
	copy ${CMAKE_BINARY_DIR}/build_${PLATFORM}/${CMAKE_BUILD_TYPE}/bin/${PREFIX}TraderCTPOpt${SUFFIX} ${EXECUTABLE_OUTPUT_PATH}/traders/
	)
ENDIF()

LIST(APPEND WT_RUNNER_POST_BUILD_COMMANDS
	COMMAND ${CMAKE_COMMAND} -E
	copy ${CMAKE_BINARY_DIR}/build_${PLATFORM}/${CMAKE_BUILD_TYPE}/bin/${PREFIX}TraderFemas${SUFFIX} ${EXECUTABLE_OUTPUT_PATH}/traders/

	COMMAND ${CMAKE_COMMAND} -E
	copy ${CMAKE_BINARY_DIR}/build_${PLATFORM}/${CMAKE_BUILD_TYPE}/bin/${PREFIX}WtExeFact${SUFFIX} ${EXECUTABLE_OUTPUT_PATH}/executer/

	COMMAND ${CMAKE_COMMAND} -E
	copy ${CMAKE_BINARY_DIR}/build_${PLATFORM}/${CMAKE_BUILD_TYPE}/bin/${PREFIX}WtDataStorage${SUFFIX} ${EXECUTABLE_OUTPUT_PATH}/

	COMMAND ${CMAKE_COMMAND} -E
	copy ${CMAKE_BINARY_DIR}/build_${PLATFORM}/${CMAKE_BUILD_TYPE}/bin/${PREFIX}WtDataStorageAD${SUFFIX} ${EXECUTABLE_OUTPUT_PATH}/

	COMMAND ${CMAKE_COMMAND} -E
	copy ${CMAKE_BINARY_DIR}/build_${PLATFORM}/${CMAKE_BUILD_TYPE}/bin/${PREFIX}WtRiskMonFact${SUFFIX} ${EXECUTABLE_OUTPUT_PATH}/

	COMMAND ${CMAKE_COMMAND} -E
	copy ${CMAKE_BINARY_DIR}/build_${PLATFORM}/${CMAKE_BUILD_TYPE}/bin/${PREFIX}WtMsgQue${SUFFIX} ${EXECUTABLE_OUTPUT_PATH}/
)

add_dependencies(WtRunner ${WT_RUNNER_POST_BUILD_DEPENDS})
add_custom_command(TARGET WtRunner POST_BUILD
	${WT_RUNNER_POST_BUILD_COMMANDS}
	COMMENT "depends modules copied")


