
#1. 确定CMake的最低版本需求
CMAKE_MINIMUM_REQUIRED(VERSION 3.20)

#2. 确定工程名
PROJECT(TestBtPorter LANGUAGES CXX)


#7. 添加源码
SET(SRCS
	main.cpp
)

SET(LIBS
	WtBtPorter
)


ADD_EXECUTABLE(TestBtPorter ${SRCS})
TARGET_LINK_LIBRARIES(TestBtPorter PRIVATE WT::fmt)
TARGET_LINK_LIBRARIES(TestBtPorter PRIVATE ${LIBS})

IF (MSVC)
ELSE()
	SET_TARGET_PROPERTIES(TestBtPorter PROPERTIES
        BUILD_RPATH_USE_ORIGIN ON)
ENDIF ()