#1. 确定CMake的最低版本需求
CMAKE_MINIMUM_REQUIRED(VERSION 3.20)

#2. 确定工程名
PROJECT(WtDtHelper LANGUAGES CXX)


#7. 添加源码
SET(SRCS
	WtDtHelper.cpp
)
SET(HDRS
	WtDtHelper.h
)

ADD_LIBRARY(WtDtHelper SHARED ${SRCS} ${HDRS})
TARGET_LINK_LIBRARIES(WtDtHelper PRIVATE WT::fmt WT::RapidJSON)

SET(LIBS
	WTSUtils
    WTSTools
)
IF (MSVC)
ELSE()
	LIST(APPEND LIBS
		WT::Platform
		${FS_LIB}
		)
ENDIF()

TARGET_LINK_LIBRARIES(WtDtHelper PUBLIC ${LIBS})
IF (MSVC)
ELSE()
	SET_TARGET_PROPERTIES(WtDtHelper PROPERTIES
		CXX_VISIBILITY_PRESET hidden
		VISIBILITY_INLINES_HIDDEN 1
        BUILD_RPATH_USE_ORIGIN ON)
ENDIF ()
		
