#1. 确定CMake的最低版本需求
CMAKE_MINIMUM_REQUIRED(VERSION 3.20)

#2. 确定工程名
PROJECT(WtMsgQue LANGUAGES CXX)


#7. 添加源码
SET(SRCS
	MQClient.cpp
	MQManager.cpp
	MQServer.cpp
	WtMsgQue.cpp
)
SET(HDRS
	MQClient.h
	MQManager.h
	MQServer.h
	PorterDefs.h
	WtMsgQue.h
)

ADD_LIBRARY(WtMsgQue SHARED ${SRCS} ${HDRS})
TARGET_LINK_LIBRARIES(WtMsgQue PRIVATE
	WT::fmt
	WT::Nanomsg
	WT::Platform
)
IF(WIN32)
	TARGET_LINK_LIBRARIES(WtMsgQue PRIVATE ws2_32 mswsock)
ENDIF()
IF (MSVC)
ELSE()
	SET_TARGET_PROPERTIES(WtMsgQue PROPERTIES
		CXX_VISIBILITY_PRESET hidden
		VISIBILITY_INLINES_HIDDEN 1
        BUILD_RPATH_USE_ORIGIN ON)
ENDIF ()
