
#1. 确定CMake的最低版本需求
CMAKE_MINIMUM_REQUIRED(VERSION 3.20)

#2. 确定工程名
PROJECT(ParserShm LANGUAGES CXX)

SET(SRC  
	${PROJECT_SOURCE_DIR}/ParserShm.cpp
	${PROJECT_SOURCE_DIR}/ParserShm.h
)

SET(LIBRARY_OUTPUT_PATH ${CMAKE_BINARY_DIR}/build_${PLATFORM}/${CMAKE_BUILD_TYPE}/bin)

ADD_LIBRARY(ParserShm SHARED ${SRC})
TARGET_LINK_LIBRARIES(ParserShm PRIVATE WT::fmt)

IF(MSVC)
	SET(LIBS )
ELSE(GNUCC)
	IF (WIN32)
		SET(LIBS
			WT::BoostThread
            ${FS_LIB}
		)
	ELSE(UNIX)
		SET(LIBS
			WT::BoostThread
			WT::BoostFilesystem
            ${FS_LIB}
		)
	ENDIF()
ENDIF()
TARGET_LINK_LIBRARIES(ParserShm PUBLIC ${LIBS})

IF (MSVC)
ELSE (GNUCC)
	SET_TARGET_PROPERTIES(ParserShm PROPERTIES
		CXX_VISIBILITY_PRESET hidden
		C_VISIBILITY_PRESET hidden
		VISIBILITY_INLINES_HIDDEN 1
        LINK_FLAGS_RELEASE -s)
ENDIF ()

