
#1. 确定CMake的最低版本需求
CMAKE_MINIMUM_REQUIRED(VERSION 3.20)

#2. 确定工程名
PROJECT(TraderYD LANGUAGES CXX)

SET(SRC  
	${PROJECT_SOURCE_DIR}/TraderYD.cpp
	${PROJECT_SOURCE_DIR}/TraderYD.h
)


ADD_LIBRARY(TraderYD SHARED ${SRC})
TARGET_LINK_LIBRARIES(TraderYD PRIVATE WT::fmt PUBLIC WT::Vendor::YD)

IF(MSVC)
ELSE()
	SET(LIBS
		WT::BoostThread
		${FS_LIB}
		WT::Platform
	)
	TARGET_LINK_LIBRARIES(TraderYD PUBLIC ${LIBS})
ENDIF()

IF (MSVC)
ELSE()
	SET_TARGET_PROPERTIES(TraderYD PROPERTIES
		CXX_VISIBILITY_PRESET hidden
		C_VISIBILITY_PRESET hidden
		VISIBILITY_INLINES_HIDDEN 1
        BUILD_RPATH_USE_ORIGIN ON)
ENDIF ()

